### ISSUE TITLE
should I use co directly??

### ISSUE THREAD

**Issue by stableShip** [mciparelli/co-express#12]
I found that we can use express with co just like:

```
router.get('/localplans', function(req, res, next){
    co(function*() {
        try {
            console.log("middleware");
            next();
        } catch (err) {
            logger.error(err);
            res.send(err);
        }
    })
}, function (req, res) {
    co(function*() {
        try {
            res.send("hello");
        } catch (err) {
            logger.error(err);
            res.send(err);
        }
    })
});

```

so I have a little confuse. Should I use co directly??

**Comment by mciparelli** [comment]
If you look at the source code + Readme you'll notice that this is just a simple tiny wrapper for express middlewares. It's been built so that you don't have to bother in importing `co` and wrapping middlewares yourself like you did above.

**Comment by stableShip** [comment]
get it, thank you
