### ISSUE TITLE
Not work with app.param

### ISSUE THREAD

**Issue by malash** [mciparelli/co-express#14]
`app.param` & error handling use both 4 length arguments.

https://github.com/mciparelli/co-express/blob/master/index.js#L6-L10
http://expressjs.com/en/api.html#app.param
http://expressjs.com/en/guide/error-handling.html

**Comment by mciparelli** [comment]
Would this help you? https://github.com/mciparelli/co-express/commit/67ccbe390bd8f23858065977b7e1460c2318ac4e

**Comment by malash** [comment]
A bad case https://github.com/malash/co-express/commit/cfb856759e4619f392960329043b75cee602111b

**Comment by mciparelli** [comment]
Fixed in v1.2.2
