### ISSUE TITLE
Module doesn't work correctly with Express 4.0 routes

### ISSUE THREAD

**Issue by dariusriggins** [mciparelli/co-express#7]
Using this new syntax, co-express doesn't wrap these correctly.

http://scotch.io/bar-talk/expressjs-4-0-new-features-and-upgrading-from-3-0

**Comment by alekseykulikov** [comment]
Refactored version of the library, that passes all 5 tests:

```js
var co = require('co')

module.exports = function wrap(gen) {
  var fn = co.wrap(gen)
  return function(req, res, next) {
    return fn(req, res, next).catch(next)
  }
}
```

Benefits:
- `co.wrap` is called only once
- avoids manipulation with `arguments`

If you wish, I can provide a PR for this.

**Comment by mciparelli** [comment]
Please do!
